version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8369:8369"
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    volumes:
      - ./backend:/app
    command: python main.py
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  frontend:
    build: ./frontend
    ports:
      - "3369:3369"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M